#File Input and Output(I/O).  Everything works on pointers

#Python can be used to perform operations on a file.(read and write data).
#Types of Files --> 1.Text files :- .txt, .docx, .log, etc
#                   2.Binary files :- .mp4, .mov, .png, .jpeg, etc

# RAM --> Volatile memory.



# Syntax : f = open("fileName" , "mode") --> mode: r(read mode) OR w(write mode) and many more. By Default read is selected.
#         data = f.read();
#         f.close()

# # Open read and close file
# file = open("Lec7Demo.txt" , "r")
# data = file.read();  # --> We can pass number as arg so it will read that must data only
# print(data) # --> prints everything written in that file
# print(type(data)) # --> <class 'str'> = stream
# file.close()


# # Few Imp Modes
# r = open or read(default)
# w = write, truncating the file first --> OverWrite measn delete the data first then add new data
# x = Create a new file and open it for writing
# a = Open for writing, appending to the end of the file if it exists
# b = Binary Mode
# t = text mode(default)
# + = open a disk file for updating (reading and writing)
# r+ = overwrites the file from starting,pointer at start, truncate
# w+ = read and overwrite, 
# a+ = read and append, pointer at end, No truncate
# !! We can make combinations also to do multiplt tasks on it read or use chatgpt to know


# # Read Methods
# file = open("Lec7Demo.txt" , "r")
# dataAll = file.read() # --> reads entire file and pointer moves to the end so thats y next line does not reads anythngs hence prints an empty string
# line1 = file.readline(); # --> reads line by line
# print(line1)   # --> So to print line 1 it should be above read()
#                # --> In the output we get a space of next line cz of "\n" 
# data = file.readlines() # --> Gives output in a List form
# print(data)  
# file.close();


# # Write methods
# file = open("Lec7Demo.txt" , "w")
# file.write("This is written in w mode") # Overwrites the entire file
# file = open("Lec7Demo.txt" , "r")
# print(file.read())
# file.close();

# file = open("Lec7Demo.txt" , "a")
# file.write("\nThis is written in a mode") # Adds the new line
# file = open("Lec7Demo.txt" , "r")
# print(file.read())
# file.close()


# # File creation
# f = open("autoGenerated.txt", "w") # --> Here file does not exists so a file will be created automatically
# f.close();



# # With keyword.
# with open("Lec7Demo.txt" , "r") as file : # as --> aliases  # With closes file automatically 
#     data = file.read()
#     print(data)
    # file.close() # --> # With closes file automatically so no need to write this



# # Deleting a file.
# Using a ""os module
# Module is like a file or code library that generally has a function we can use to delete file
# Syntax : import os; os.remove("filename")

# # To delete we use OS
# import os;
# os.remove("autoGenerated.txt") # -->Deletes the file

# !!Note:
# To use python modules whcich are not preinstalled we can load it using 
# !!!! --> ""pip3/pip install modulename"" pip = package installed for python, eg : pip install tenserflow --> used to built neural network in machine learning


# #Q1 : Create a new file practice.txt and add some data in it
# f = open("practise.txt" , "w");
# f.write("Hi everyone\nWe are learning File I/O\nusing Python.\nI like programming in Python.")
# f.close();

# # #Q2 : Write a function that replaces python with java.
# f = open("practise.txt" , "r");
# data = f.read();

# newData = data.replace("Python", "Java")
# print(newData);

# f = open("practise.txt" , "w");
# f.write(newData);

# #Q3: Search if the word "learning" exist or not.
# def checkWord() :
#     word = "learning"
#     with open("practise.txt" , "r")as f :
#         data = f.read();

#         if(data.find(word) != -1) : # ---> or we can write if(word in data)
#             print("Found")
#         else :
#             print("Not found")

# checkWord();

# #Q4 : WAF to find in which line does the word learning occurs first print -1 if not found.
# def findLine() :
#     word = "learning"
#     data = True
#     lineNum = 1
#     with open("practise.txt" , "r")as f :
#         while data :
#             data = f.readline();
#             if(word in data) :
#                 print(lineNum)
#                 return
#             lineNum += 1

#     return -1

# ans = findLine();
# print(ans);


# #Q5 : From a file containig nums seperated by comma, print count of even numbers.
# with open("practise.txt", "r") as f :
#     data = f.read()
#     print(data)

#     #Method 1
#     nums = data.split(",")
#     print(nums)
#     count = 0
#     for val in nums :
#         if(int(val) % 2 == 0) :
#             count += 1;
#     print(count)

#     #Method 2
#     num = ""
#     count = 0
#     for i in range(len(data)) :
#         if(data[i] == ",") :
#             if(int(num) % 2 == 0) :
#                 count += 1
#                 num = ""
#         else :
#             num += data[i]
#     print(count)
